# Imports

In [14]:
%%capture
# Normally using pip install unsloth is enough

# Temporarily as of Jan 31st 2025, Colab has some issues with Pytorch
# Using pip install unsloth will take 3 minutes, whilst the below takes <1 minute:
!pip install --no-deps bitsandbytes accelerate xformers==0.0.29.post2 peft trl triton
!pip install --no-deps cut_cross_entropy unsloth_zoo
!pip install sentencepiece protobuf datasets huggingface_hub hf_transfer
!pip install --no-deps unsloth

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
BASE_PATH = './'
PROJECT_NAME = 'mesos'

In [3]:
# deterministic sampling 80/20 train/test
import pandas as pd

df_all_tickets = pd.read_csv(BASE_PATH + f'datasets/{PROJECT_NAME}.csv')

train_split_point = int(len(df_all_tickets) * 0.8)

test_tasks = df_all_tickets.iloc[train_split_point:,]

In [4]:
test_tasks = test_tasks.rename(columns={'Custom field (Story Points)': 'storypoint'})
test_tasks

,Unnamed: 0,Summary,storypoint,Assignee_count,Reporter_count,Creator_count
3456,3456,First-order reconciliation of internal service...,14.0,0.073780,0.874542,0.901099
3457,3457,Install supporting services,12.0,0.212259,0.874542,0.901099
3458,3458,Design transfer mechanism for DR tool.,5.0,0.212259,0.874542,0.901099
3459,3459,Monitor Globus transfer tasks,14.0,0.212259,0.874542,0.901099
3460,3460,Process refinement and improvement.,10.0,0.212259,0.874542,0.901099
...,...,...,...,...,...,...
4315,4315,Develop DM requirements for processing crowded...,20.0,0.828604,0.980769,0.980769
4316,4316,Review SpanSet & Footprint API,2.0,0.828604,1.000000,1.000000
4317,4317,Investigate using both monotonicity and symmetry,4.0,0.333712,0.260073,0.260073
4318,4318,Enable fake sources on coadds,6.0,0.334847,1.000000,1.000000
4319,4319,Review literature on CModel,2.0,0.334847,1.000000,1.000000

# Inference

In [ ]:
# Create symbolic link
import os


model_name = f"{PROJECT_NAME}_Llama-3.1-8B-Instruct_e10_msl2048_r8"
# for base model, use this instead:
# model_name = f"{PROJECT_NAME}_Llama-3.1-8B-Instruct_base-model"

source_path = os.path.join(BASE_PATH, "models", model_name)
target_path = os.path.join("./", model_name)

!ln -s "{source_path}" "{target_path}"

In [15]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# model_name = "unsloth/Llama-3.1-8B-Instruct"
model_peft, tokenizer = FastLanguageModel.from_pretrained(
    model_name = model_name,
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    # token = "hf_...", # use one if using gated models like meta-llama/Llama-2-7b-hf
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2025.5.9: Fast Llama patching. Transformers: 4.52.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.557 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.0. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/5.96G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/55.5k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

In [1]:
system_prompt = """You are an expert software development effort estimator. Given a software development issue summary, predict the effort in story points."""
user_prompt = """### Summary:
{}"""
assistant_prompt = """My estimated story point is: {}"""


def generate_convo(row):
  # {"role": "system", "content": "You are an assistant"}
  # {"role": "user", "content": "What is 2+2?"}
  # {"role": "assistant", "content": "It's 4."}

  convo_template = {
    "conversations": [
      {
          "role": "system",
          "content": system_prompt
      },
      {
          "role": "user",
          "content": user_prompt.format(
                          row['Summary'],
                      )
      }
    ]
  }

  return convo_template

import json

# print(json.dumps(generate_convo(test_tasks.iloc[0]), indent=2))

In [17]:
from collections import Counter

def most_frequent(lst):
    return Counter(lst).most_common(1)[0][0]

In [49]:
import re

def get_answer(model, tokenizer, task):
  convo = generate_convo(task)
  messages = convo["conversations"]

  inputs = tokenizer.apply_chat_template(
      messages,
      tokenize = False,
      add_generation_prompt = True, # Must add for generation
      # return_tensors = "pt",
  )
  inputs += "My estimated story point is: "
  inputs = tokenizer(inputs, return_tensors="pt")
  input_ids = inputs['input_ids'].to("cuda")
  attention_mask = inputs['attention_mask'].to("cuda")

  FastLanguageModel.for_inference(model) # Enable native 2x faster inference
  # output = model.generate(input_ids = inputs, max_new_tokens = 5, top_k=1)
  # text = tokenizer.decode(output[0], skip_special_tokens=False)
  outputs = model.generate(
    input_ids = input_ids,
    attention_mask = attention_mask,
    max_new_tokens = 5,
    top_k=1
  )
  text = tokenizer.decode(outputs[0])

  return text

def parse_estimation(answer_text):
    estimation = re.search(r'My estimated story point is:\s*(\d+)', answer_text)
    # estimation = re.search(r'My estimated story point is:\s*(\d+\.?\d*)', answer_text)

    if estimation:
        return estimation.group(1)
    else:
        return 0

In [50]:
import pandas as pd
import random

all_estimations = []
target_dataset = test_tasks
progress_count = 0

print(f"Benchmarking on {len(target_dataset)} questions")

for index, item in target_dataset.iterrows():
    task_id = item['Summary']
    correct_answer = item['storypoint']

    progress_count += 1
    print(f"[{progress_count}/{len(target_dataset)}] - {task_id}")

    llm_output = get_answer(model_peft, tokenizer, item)

    all_estimations.append(
        {
            'task_id': task_id,
            'correct_answer': correct_answer,
            'llm_answer': parse_estimation(llm_output),
            'llm_response': llm_output,
        }
    )


df_results = pd.DataFrame(all_estimations)
df_results['matched'] = df_results['correct_answer'] == df_results['llm_answer']

df_results.head()

Benchmarking on 864 questions
[1/864] - First-order reconciliation of internal service architecture with high-level services
[2/864] - Install supporting services
[3/864] - Design transfer mechanism for DR tool.
[4/864] - Monitor Globus transfer tasks
[5/864] - Process refinement and improvement.
[6/864] - Service Management & Emergent Work  (December)
[7/864] - Change SQuaSH to store JSON as a BLOB/TEXT in MariaDB 10.1+
[8/864] - DM-wide replanning - December: further development of NCSA WBS
[9/864] - Ops planning - December: assess reviewers feedback, consider descope options
[10/864] - Commissioning planning - December: contributions to commissioning plan document
[11/864] - Ops planning - January
[12/864] - Commissioning planning - January
[13/864] - DM-wide replanning - January
[14/864] - migrate squash production DB to MariaDB 10.1.x
[15/864] - purge unused jenkins plugins / fully manage all plugins
[16/864] - jenkins master unstable
[17/864] - Remove dependency on CAT package and make database setup optional
[18/864] - ctrl_stats fails tests in 2017
[19/864] - ctrl_stats doesn't calculate year to next year progress properly
[20/864] - Use an existing qserv_run_dir with a new Qserv instance/binary
[21/864] - evaluate creation / installation of eups distrib 'tarball' packages
[22/864] - Add TE1 and TE2 KPMs to validate_drp using code developed in DM-3040
[23/864] - Plot the data flow of a jointcal example
[24/864] - Plan Prototype Warped Image Comparision
[25/864] - Update developer guide to describe package build directory
[26/864] - Update eupspkg to support _build/ directory
[27/864] - Update existing packages to reflect _build/ directory and .gitignore entries
[28/864] - Original plot does not abort and over writes active plot
[29/864] - Change warpImage and warpExposure to take shared_ptrs
[30/864] - Create NMF deblender plugin
[31/864] - fix lsst-sims installation instructions on pipelines.lsst.io
[32/864] - Set darktime in makeRawVisitInfo
[33/864] - Update singleFrameDriver following changes to reference catalogs
[34/864] - Extend Alert Production prototype with new index type
[35/864] - Performance plots with AP prototype on SSD
[36/864] - Documenting using emoji reactions in GitHub code reviews
[37/864] - Create deprecation decorator and doc update
[38/864] - Add deprecation procedure to dev guide
[39/864] - Small bug in describing the usesimplePsf config var for charImgTask
[40/864] - Create cookiecutter template for api.lsst.codes microservices
[41/864] - obs_cfht table file uses envAppend
[42/864] - Wrap new Footprints with pybind11 and create python unit test
[43/864] - evaluate creation / installation of eups distrib 'tarball' packages #2
[44/864] - Implement bokeh apps helper methods to read data from the SQUASH API
[45/864] - BaseSourceSelector._isBad() should use Keys instead of string fields
[46/864] - writing jointcal output is slow due to dataRef lookup
[47/864] - unset BASH_ENV in newinstall.sh or surrounding instructions
[48/864] - Revise Python Style Guide for RFC-107 (79 character docstring lengths)
[49/864] - Incorrect binning in overscan spline interpolation
[50/864] - Delete Crop.java and CropTest.java
[51/864] - Automatic Mask overlays
[52/864] - Test/implement which badFlags are appropriate for matcherSourceSelector
[53/864] - Transfer content from SWUG pages to PLI (pipelines.lsst.io)
[54/864] - SQL constraint catalog search doesn't work
[55/864] - wmgr database connection leak
[56/864] - Fix plotAMx display of spec
[57/864] - Bootstrapper microservice
[58/864] - Rebase pybind11 branch onto latest master
[59/864] - Open up LSST software mailing lists
[60/864] - Publish Winter 2014 binaries
[61/864] - Update PhoSim tutorial to use CatSim for creating instance catalogs
[62/864] - jenkins slave password exposed in process table
[63/864] - Find & archive José Garmilla's S/G separation code
[64/864] - Fix & document S/G code
[65/864] - Wrap clone for all table classes
[66/864] - Check uses of darktime for NAN
[67/864] - Shared stack build failures on lsst-dev01
[68/864] - git-lfs related lsstsw installation error on macOS Sierra
[69/864] - Update dev guide to clarify C++ construction syntax (implements RFC-242)
[70/864] - Microservice bootstrapper doesn't handle maketrans() correctly
[71/864] - Investigate stack-like installation requirements for Pegasus
[72/864] - Make simpleShape less chatty
[73/864] - Refactor FileInfo and FileData classes into one class
[74/864] - Re-enable MKL/OpenBLAS
[75/864] - Add 2-d version of cppIndex
[76/864] - Drivers should be able to be made less verbose about eups
[77/864] - Investigate downcasting of Table and Record types in pybind11
[78/864] - Advanced study on k8s (kubernetes)
[79/864] - Create common S3 upload/interface Python package for LSST the Docs microservices and clients
[80/864] - Add LTD Dasher interaction into LTD Keeper
[81/864] - LTD Dasher: create microservice skeleton
[82/864] - Implement MVP for edition and build static dashboards in LTD Dasher
[83/864] - Amend Python test naming guidelines in Developer Guide Following RFC-229
[84/864] - Firefly IPAC table reader should handle data type "real"
[85/864] - Connection strings in imgserv should come from a config file.
[86/864] - Process the HSC RC dataset with the latest hscPipe 4.0.5
[87/864] - SourceDetectionTask should only add flags.negative if config.thresholdParity == "both"
[88/864] - Setup and configure ESXi on lsst-dm-mac-2
[89/864] - Create MacOS Sierra VM for ESXi.
[90/864] - Update, upgrade and thin VMs on the Mac Pro ESXis
[91/864] - Update post_qa to shim blobs, measurement metadata and metric definitions to SQUASH API
[92/864] - Generate full set of HSC PSF-matched temp exps for testing
[93/864] - reorder butler init to be more incremental when building Repositories
[94/864] - Make indexed reference loader agnostic to ingest name
[95/864] - Reimplement model/residuals display for CModel
[96/864] - Remove or revive bitrotted code in meas_modelfit
[97/864] - change CameraMapper to not migrate backups from parent repositories to the output folder
[98/864] - Enable autolinking in Doxygen
[99/864] - Add flags for sources used in astrometric and photometric calibration
[100/864] - update jenkins osx build slave configuration
[101/864] - Run singleFrameDriver with the HSC COSMOS dataset on Verification Cluster
[102/864] - DarkCombineTask broken
[103/864] - Add deprecation_warning capability to upstream pybind11
[104/864] - Check int vs float interoperability in pybind11 afw.geom
[105/864] - Option to apply all images in image rotation panel is inconsistent with the use of the lock feature
[106/864] - Create test suite for pipe_drivers
[107/864] - Add metadata access to get wcs, visitInfo, and calib from a calexp dataset
[108/864] - Copy PS1 catalog to /datasets
[109/864] - Per WBS breakout of DRP actuals for December 2016
[110/864] - Audit pybind11 port for outstanding technical debt
[111/864] - Fix memory leak in SpanSets Persistence
[112/864] - adapt jenkins to lsst-dev[-old] retirement
[113/864] - Create chatops service for cookiecutter microservice
[114/864] - Experiment with ProcessPoolExecutor for reading/writing jointcal results
[115/864] - Chart container tracking an active table in a table group
[116/864] - Check data loading speed for ForcedSources
[117/864] - lsstsw/bin/deploy broken due to missing conda package versions
[118/864] - Make standard measurement algorithms less chatty
[119/864] - Keep LS as only periodogram calculation option
[120/864] - Backup and get service for lsst-dm-mac
[121/864] - labels for tab were cutoff a little at the bottom
[122/864] - testExposure.testGetWcs docstring is wrong, and tests should be assertIsNone
[123/864] - Remove RFD options from JIRA RFC
[124/864] - Modify community as needed to support RFDs
[125/864] - Add post-repository-creation hooks to cookiecutter services
[126/864] - Add Python property guidelines to dev guide
[127/864] - Move pybind11 how-to technote to dev guide
[128/864] - Kubernetes setup and knowledge transfer
[129/864] - Create a simplified workflow based on the ciHsc workflow
[130/864] - Fix "default" refcat filter in jointcal.run()
[131/864] - Attend LSST Calibration Workshop at Harvard
[132/864] - Add more periodogram algorithms to the Time Series Viewer
[133/864] - Fix lsst-sphinx-bootstrap-theme deployment
[134/864] - Update mariadb eups packages
[135/864] - Merge pybind11 branches to master
[136/864] - Update the import package in LSSTFileGroupProcessor
[137/864] - PUB JIRA tickets never resolve
[138/864] - Make SpanSet operator templates more generic
[139/864] - Make sqrbot reply to interlocutor
[140/864] - Investigate isotropic footprint growing/dilating behavior: HSC vs. LSST
[141/864] - Investigate distribution of footprint sizes: HSC vs. LSST
[142/864] - Create ellipticity residuals quiver plots
[143/864] - Provide Task documentation for DipoleMeasurementTask
[144/864] - Investigate source of systematic difference of model psf trace radii: HSC vs. LSST
[145/864] - Add rotator information to HSC VisitInfo
[146/864] - Determine strategy for dealing with butler proxies in pybind11
[147/864] - the bias ingestion should not care about the filter
[148/864] - eups distrib: qserv_testdata is not setup
[149/864] - Near-term calexp cutout API for imgserv
[150/864] - Failure to persist footprints with SOURCE_IO_NO_HEAVY_FOOTPRINTS
[151/864] - Investigate and resolve disk space/quota issues
[152/864] - Wrap astshim using pybind11
[153/864] - Convert validateDrp.py into a monolithic SuperTask (MVP)
[154/864] - Provide Task documentation for PsfMatchTask
[155/864] - matcherSourceSelector incorrectly uses nChild and footprints in isMultiple test.
[156/864] - Investigate slow linking of pybind11 modules
[157/864] - Fix broken travis-ci
[158/864] - streamline generation of qserv_latest eupspkgs
[159/864] - Make SGS: plotsScript.py: makeRachelPlots work!
[160/864] - qserv_distrib does not setup qserv_testdata
[161/864] - Configure system
[162/864] - Respond to user cofiguration needs
[163/864] - Security Vetting
[164/864] - Provide Task documentation for ImagePsfMatchTask
[165/864] - Apply second round of Robert's LDM-151 comments
[166/864] - Act on Robert and Zeljko's requests for tweaks LDM-151 from yesterday's chat
[167/864] - Refactor astshim so objects hold a unique_ptr to the underlying AST object and are non-copyable
[168/864] - Move fromDbToTruth.py from sgs -> sgsupervised and merge in contents of makeTrainSet.py
[169/864] - bulk rename of jointcal variables
[170/864] - Include CBP coordinate transformation system in LDM-151
[171/864] - Reinstall ESXi on lsst-dm-mac.lsst.org
[172/864] - Pythonic type names in pybind11 docstrings
[173/864] - Processing run on ctio .9-m, January 2017
[174/864] - Provide Task documentation for SnapPsfMatchTask
[175/864] - Ensure __str__ and __repr__ copied from Swig
[176/864] - Lomb-scargle step method input default values, valid ranges and labels need more work
[177/864] - calibrateTask.py example not working on current stack
[178/864] - Create 2D monotonic operator for NMF deblender
[179/864] - Check landscape.io is working with lsst/qserv repos
[180/864] - Autoupdating and self-publishing API documentation for imgserv
[181/864] - Implement global sky subtraction
[182/864] - Provide Task documentation for AssembleCcdTask
[183/864] - Implement file transfer in DR tool
[184/864] - Test file transfer for DR tool
[185/864] - Wrap ci_hsc with pybind11
[186/864] - Write release notes for pybind11 port
[187/864] - working directory recovery in pegasus investigation
[188/864] - Catch-and-ignore should not apply to any exception
[189/864] - Provide Task documentation for IsrTask
[190/864] - astrometry_net_data version has regressed to 8.0.0
[191/864] - magnitude shoud be plotted in decrease order in period finding layout
[192/864] - newinstall.sh broken by conda package removal from public channels
[193/864] - Add feature to overlay the searched position on the coverage image.
[194/864] - Help IN2P3 scientist to load stack processed data inside Qserv
[195/864] - Changes in the SQUASH API to upload metrics definition
[196/864] - Provide HSC test data for deblending
[197/864] - Provide high-stellar-density fields for deblender testing
[198/864] - Implement PSF convolution operator in 2D
[199/864] - Implement NMF with alternating least squares
[200/864] - Implement validation metrics for NMF outputs
[201/864] - Study deblending techniques
[202/864] - Cleanup pybind11 code in afw
[203/864] - Higher order models for jointcal photometric solutions
[204/864] - Remove workaround and fix pickling for BasisTypeEnum
[205/864] - Create hscIsr.py script
[206/864] - port jointcal to pybind11
[207/864] - Cleanup pybind11 code in core meas and ip packages
[208/864] - Cleanup pybind11 remaining code
[209/864] - Implement new spatially-variable PhotoCalib model
[210/864] - design new Calib object and interface
[211/864] - Investigate meas_mosiac's photometric model
[212/864] - Implement improved jointcal photometric fit
[213/864] - cutout size parameter is not passed in the request by the download dialog
[214/864] - runIsrTask.py example (also) not working on current stack
[215/864] - Plan for S17-3 sprint
[216/864] - Plan for S17-4 sprint
[217/864] - tests/testPsfDetermination.py has a broken test
[218/864] - Resolve variances and/or provide narratives for LSST ME 16-12
[219/864] - Resolve variances and/or provide narratives for LSST ME 17-01
[220/864] - Monthly narrative for December 2016
[221/864] - DRP monthly narrative for January 2017
[222/864] - Recruitment in January 2017
[223/864] - Recruitment in Feb 2017
[224/864] - Precision of expression columns
[225/864] - Change Executor's data passing mechanism
[226/864] - Mid-cycle replan
[227/864] - Allow Executor to work with pre-exisiting dataset repositories
[228/864] - Investigate whether DRP team members can ticket personal work on JIRA
[229/864] - Fix gaps in afw test coverage
[230/864] - Remove makeVisitInfo
[231/864] - Remove afw::image::ImageSlice
[232/864] - afw::math::Function should be pure-virtual
[233/864] - Replace afw::geom::Functor with std::function
[234/864] - Convert some afw enums into class enums
[235/864] - Use ndarray instead of std::vector in RadialXYTransform
[236/864] - Use ndarray instead of std::vector in afw::math::Function and Kernel
[237/864] - Delegate to Astropy for coordinate stringification
[238/864] - Replace afw.geom.Angle with Astropy Quantities in Python
[239/864] - Revisit wrapping C++ Control objects into Python Config objects.
[240/864] - Refactor Fastly API client from LTD Keeper to LTD Conveyor
[241/864] - Rewrite ndarray pybind11 type_casters to avoid numpy C API
[242/864] - Add VERBOSE logging option to log
[243/864] - Pad Psfs before PSF-matching
[244/864] - implement a fixed-length weekly tag format
[245/864] - Add default constructor to new Footprints
[246/864] - Use Pegasus to do ProcessCcd with a subset of HSC COSMOS data on /datasets/hsc
[247/864] - Delete FlipLR  class since it is no longer used
[248/864] - Onboarding form Tim Morton
[249/864] - Update local onboarding guide
[250/864] - squash KPM plots should label the time axis with a timezone
[251/864] - squash KPM plot points are ~8 hours ahead of UTC
[252/864] - Replacing JS package manager npm with yarn
[253/864] - perodic `mysqldump`s of squash qadb
[254/864] - Implement search processor(s) to support All Sky mode
[255/864] - Implement "All Sky" mode in LSST catalog and image search panels
[256/864] - Modify FlagHandler C++ and flagDecorator.py to make flag identification robust
[257/864] - finish KeyMap and fix _decompose in astshim
[258/864] - Rebase pybind11 branch onto latest master
[259/864] - Investigate bimodal distribution of footprint sizes for "stars"
[260/864] - Prepare for IRSA Time series viewer release
[261/864] - Firefly is not working in Windows browser IE 11
[262/864] - Fix Search on developer.lsst.io
[263/864] - VM Cluster machine reset
[264/864] - Modify pybind11 sconsUtils to only prepend underscore if not already present
[265/864] - add hsc dataset to jenkins validate_drp job
[266/864] - Provide Task documentation for SourceDeblendTask
[267/864] - Investigate exception handling in PYBIND11_PLUGIN
[268/864] - Update git-lfs repositories to address deprecations.
[269/864] - Use C++ for OCS Bridge to DMCS subscribe as well as Publish
[270/864] - Test module for DMCS
[271/864] - Test for OCS Bridge
[272/864] - Add Audit capability to prompt processing
[273/864] - Operations planning - February
[274/864] - DM-wide replanning - February
[275/864] - Upgrade flask to 0.12 (stable)
[276/864] - Add utility code for wrapping dict-like C++ objects
[277/864] - Provide Task documentation for CmdLineTask
[278/864] - Add ability to security lock specific RFCs
[279/864] - Downloaded table when columns are filtered one-by-one contains all the columns regardles user selection
[280/864] - Build Python doc using Sphinx
[281/864] - Port obs_monocam to pybind11
[282/864] - Wrap obs_cfht with pybind11 instead of swig
[283/864] - Wrap obs_decam with pybind11 instead of swig
[284/864] - Wrap ctrl_platform_lsstvc with pybind11 instead of swig
[285/864] - Wrap cat with pybind11 instead of swig
[286/864] - Provide Task documentation for RepairTask
[287/864] - Wrap ctrl_events with pybind11 instead of swig
[288/864] - Wrap sphgeom with pybind11 instead of swig
[289/864] - Implement forced photometry server-side extension in PDAC
[290/864] - Update FGCM fit parameter format
[291/864] - Port microservices to uwsgi
[292/864] - How to write your own command line task, including how-to-retarget sub-tasks
[293/864] - squash support for multiple filters per dataset
[294/864] - makeCamera.py has undefined variables
[295/864] - Get jointcal to work with pytest
[296/864] - The stripMetadata argument of makeWcs doesn't work reliably
[297/864] - Add nginx logging into git-lfs
[298/864] - Improve install/configuration/tests documentation and migrate it to reST format
[299/864] - Implement parallel processing in L1DB prototype
[300/864] - Install LSST stack on Perseus
[301/864] - Provide feedback on SUIT code
[302/864] - Per WBS breakout of DRP actuals for January 2017
[303/864] - Accounts for DRP team members on Perseus
[304/864] - Per WBS breakout of DRP actuals for February 2017
[305/864] - Per WBS breakout of DRP actuals for March 2017
[306/864] - Per WBS breakout of DRP actuals for April 2017
[307/864] - Redesign tape tabs for feedback
[308/864] - Draft plan for PoC
[309/864] - Review and publish
[310/864] - obs_decam should not call stripWcsKeywords
[311/864] - weekly tag/release build of w_2017_6 failed: flask
[312/864] - meas_base tests broken with NumPy 1.12
[313/864] - Creates online help for SUIT
[314/864] - Get a microservice logging to ELK stack
[315/864] - Fine tune CEPH for a few worker nodes
[316/864] - Finish query cancellation
[317/864] - Document LSST stack installations on Princeton clusters
[318/864] - Clean up time series viewer
[319/864] - Create IFE app for Time series viewer
[320/864] - Resolve DM on-boarding process with coordination between Project IT, NCSA, DM T/CAMs and Admin
[321/864] - Minimal support for parallel execution of SuperTask
[322/864] - Photometric calibration uses a column "flux" not the specified filter unless a colour term is active
[323/864] - Create Nginx reverse proxy for DAX webservices
[324/864] - monocamIngestImages.py is vestigial
[325/864] - Complete LCR-836 (typographic correction to LSE-69)
[326/864] - Create obs package for PTF/ZTF
[327/864] - histogram option update (input dialog and server support)
[328/864] - scatter and line chart zoom changed when changing between "points" and "connected points"
[329/864] - Firefly has not been bootstrapped as uncaught exception
[330/864] - Both `DIAExp` and `DiffExp` are used for difference images
[331/864] - label change requests for Firefly/IRSA viewer

,task_id,correct_answer,llm_answer,llm_response,matched
0,First-order reconciliation of internal service...,14.0,8,<|begin_of_text|><|begin_of_text|><|start_head...,False
1,Install supporting services,12.0,8,<|begin_of_text|><|begin_of_text|><|start_head...,False
2,Design transfer mechanism for DR tool.,5.0,8,<|begin_of_text|><|begin_of_text|><|start_head...,False
3,Monitor Globus transfer tasks,14.0,8,<|begin_of_text|><|begin_of_text|><|start_head...,False
4,Process refinement and improvement.,10.0,5,<|begin_of_text|><|begin_of_text|><|start_head...,False

In [55]:
df_results.to_csv(BASE_PATH + f"results/{model_name.replace('/', '-')}.csv", index=False)
print(BASE_PATH + f"results/{model_name.replace('/', '-')}.csv")

In [53]:
df_results['llm_answer'] = pd.to_numeric(df_results['llm_answer'], errors='coerce')
df_results['correct_answer'] = pd.to_numeric(df_results['correct_answer'], errors='coerce')

In [54]:
import numpy as np

def calculate_mae(actual, predicted):
    actual = np.array(actual)
    predicted = np.array(predicted)
    return np.mean(np.abs(actual - predicted))

def calculate_mmre(actual, predicted):
    actual = np.array(actual)
    predicted = np.array(predicted)

    relative_errors = np.abs(actual - predicted) / actual
    mmre = np.mean(relative_errors)
    return mmre

def calculate_pred(actual, predicted, threshold=0.50):
    actual = np.array(actual)
    predicted = np.array(predicted)

    relative_errors = np.abs(actual - predicted) / actual
    pred = np.mean(relative_errors <= threshold)
    return pred

actual_values = df_results['correct_answer'].tolist()
predicted_values = df_results['llm_answer'].tolist()
mae = calculate_mae(actual_values, predicted_values)
mmre = calculate_mmre(actual_values, predicted_values)
pred = calculate_pred(actual_values, predicted_values, 0.5)
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Magnitude of Relative Error (MMRE): {mmre}")
print(f"Prediction within 50% of actual value (PRED(50)): {pred}")

Mean Absolute Error (MAE): 17.053712962962962
Mean Magnitude of Relative Error (MMRE): 11.698226047820548
Prediction within 50% of actual value (PRED(50)): 0.1574074074074074